[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.default.invariant]
runs = 512          
depth = 500       
fail_on_revert = false

[rpc_endpoints]
base_mainnet = "${ALCHEMY_BASE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
